services:
  php-cli:
    build:
      context: ./docker/php-cli
    links:
      - database
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-b24phpLibTest}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-b24phpLibTest}
      POSTGRES_USER: ${POSTGRES_USER:-b24phpLibTest}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    container_name: bitrix24-php-lib-test-database
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes:
      - ./Init Database:/docker-entrypoint-initdb.d
      - ./docker/db:/var/lib/postgresql/data
