on:
  push:
  pull_request:

name: PHPStan lint checks

jobs:
  static-analysis:
    name: "PHPStan"
    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.3"
        dependencies: [ highest ]
        operating-system: [ ubuntu-latest]

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          extensions: json, bcmath, curl, intl, mbstring
          tools: composer:v2

      - name: "Install lowest dependencies"
        if: ${{ matrix.dependencies == 'lowest' }}
        run: "composer update --prefer-lowest --no-interaction --no-progress --no-suggest"

      - name: "Install highest dependencies"
        if: ${{ matrix.dependencies == 'highest' }}
        run: "composer update --no-interaction --no-progress --no-suggest"

      - name: "PHPStan"
        run: "vendor/bin/phpstan --memory-limit=2G analyse"

      - name: "is PHPStan check succeeded"
        if: ${{ success() }}
        run: |
          echo '✅ PHPStan check pass, congratulations!'

      - name: "is PHPStan check failed"
        if: ${{ failure() }}
        run: |
          echo '::error:: ❗️ PHPStan check failed (╯°益°)╯彡┻━┻'